### ISSUE TITLE
Missing LICENSE

### ISSUE THREAD

**Issue by TechnologyClassroom** [iwanrun/blackmesa_ascii#1]
I see you have no LICENSE file for this project.  The default is copyright.

I would suggest releasing the code under the GPL-3.0-or-later or AGPL-3.0-or-later license so that others are encouraged to contribute changes back to your project.

**Comment by ghost** [comment]
Alternatively a permissive MIT license could work.

**Comment by iwanrun** [comment]
Thanks for notifying me, I've added an MIT license because I want people to do whatever they would like with the program.
